name=Samsung SmartThings
version=1.5.5
sentence=Samsung SmartThings
paragraph=Support for Samsung SmartThings
category=Device Control
url=https://github.com/bafi21/st-device-sdk-c
architectures=esp8266,esp32